name: 'analytics'
version: '1.0.0'
config-version: 2

profile: 'stock_platform_profile'

model-paths: ["models"]
macro-paths: ["macros"]

dispatch:
  - macro_namespace: dbt
    search_order: ['analytics', 'dbt'] # 'analytics' first ensures our overrides are used

models:
  analytics:
    +materialized: table

quoting:
  database: false
  schema: false
  identifier: false  # Fixed the spelling here