name: 'analytics'
version: '1.0.0'
config-version: 2

profile: 'stock_platform_profile'

model-paths: ["models"]
macro-paths: ["macros"]

# Move this to the very bottom or very top, ensuring no indentation
dispatch:
  - macro_namespace: dbt
    search_order: ['analytics', 'postgres', 'dbt'] # Added 'postgres' here explicitly

models:
  analytics:
    +materialized: table
quoting:
  database: false
  schema: false
  identifier: false    