FROM python:3.10-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt-get/lists/*

RUN pip install --no-cache-dir \
    dbt-core==1.7.10 \
    dbt-postgres==1.7.10 \
    protobuf==4.25.3

WORKDIR /usr/app
ENTRYPOINT ["dbt"]