# analytics/profiles.yml
stock_platform_profile:
  target: dev
  outputs:
    dev:
      type: postgres  # We use postgres because it's stable and wire-compatible
      host: host.docker.internal
      port: 8812
      user: admin
      password: quest
      dbname: qdb
      schema: public
      search_path: public # <--- Add this
      threads: 1