version: 2

models:
  - name: btcusdt_prices
    description: "Bitcoin price data with AI-generated forecasts"
    columns:
      - name: timestamp
        description: "Designated timestamp for QuestDB"
        tests:
          - not_null
          - questdb_unique  # Matches your custom test implementation

      - name: close
        description: "Closing price (must be positive)"
        tests:
          - not_null
          # Standard dbt test to ensure price is always > 0
          - accepted_range:
              min_value: 0.00000001 

      - name: final_forecast
        description: "AI-generated price forecast"
        tests:
          - not_null
      - name: btcusdt_prices
        tests:
          - unique:
              column_name: "(timestamp || '-' || price)" # Simple way to check for duplicate entries